version: '3.9'
services:
  todo-client:
    build:
      context: ./todolists-frontend
      dockerfile: Dockerfile
    volumes:
      - ~/.yalc:/src/app/node_modules/.yalc:ro
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
    command: ["npm", "start"]
    depends_on:
      - todo-server

  todo-server:
    build:
      context: ./todo-lists
      dockerfile: Dockerfile
    volumes:
      - ~/.yalc:/app/node_modules/.yalc:ro
    environment:
      - PORT=3000
    ports:
      - "3006:3006"
    command: ["fastify", "start", "-l", "info", "dist/app.js"]
